const FPSConfig = {
  ARENA_SIZE: 40,
  WALL_HEIGHT: 6,
  GRAVITY: -20,
  JUMP_SPEED: 8,
  MOUSE_SENSITIVITY: 0.0015,
  SYNC_RATE: 50,
  PLAYER_HEIGHT: 1.6,
  PITCH_LIMIT: Math.PI / 2.5,
  COUNTDOWN_INTERVAL: 800,
  TRACER_DURATION: 50,
  DAMAGE_FLASH_DURATION: 100,
  HIT_MARKER_DURATION: 100,
};
