const PIECE_STATS = {
  p: {
    name: 'Pawn',
    hp: 150,
    speed: 12,
    jumpSpeed: 6,
    weapon: {
      type: 'pistol',
      damage: 12,
      fireRate: 300,
      magSize: 12,
      reloadTime: 1500,
      auto: false,
      sounds: { fire: 'shoot', reload: 'reload' },
    },
  },
  n: {
    name: 'Knight',
    hp: 200,
    speed: 12,
    jumpSpeed: 11,
    weapon: {
      type: 'bow',
      damageMin: 15,
      damageMax: 45,
      chargeTime: 1500,
      minChargeTime: 400,
      fireRate: 0,
      magSize: Infinity,
      reloadTime: 0,
      auto: false,
      sounds: { draw: 'bowDraw', fire: 'bowRelease' },
    },
  },
  b: {
    name: 'Bishop',
    hp: 275,
    speed: 7,
    jumpSpeed: 8,
    weapon: {
      type: 'shotgun',
      damagePerPellet: 8,
      pelletCount: 6,
      spread: 0.08,
      falloffStart: 8,
      falloffEnd: 20,
      fireRate: 800,
      magSize: 5,
      reloadTime: 600,
      reloadPerShell: true,
      auto: false,
      sounds: { fire: 'shotgunFire', pump: 'shotgunPump', reload: 'shotgunShell' },
    },
  },
  r: {
    name: 'Rook',
    hp: 350,
    speed: 8,
    jumpSpeed: 9,
    weapon: {
      type: 'sniper',
      damage: 70,
      fireRate: 1200,
      magSize: 5,
      reloadTime: 3500,
      auto: false,
      unscopedSpread: 0.15,
      jumpingSpread: 0.3,
      sounds: { fire: 'sniperFire', bolt: 'sniperBolt', scope: 'sniperScope', reload: 'sniperReload' },
    },
  },
  q: {
    name: 'Queen',
    hp: 425,
    speed: 6,
    jumpSpeed: 7,
    weapon: {
      type: 'ar',
      damage: 14,
      fireRate: 100,
      magSize: 30,
      reloadTime: 2800,
      auto: true,
      adsSpreadReduction: 0.5,
      sounds: { fire: 'arFire', reload: 'arReload' },
    },
  },
  k: {
    name: 'King',
    hp: 500,
    speed: 6,
    jumpSpeed: 7,
    weapon: {
      type: 'deagle',
      damage: 45,
      fireRate: 500,
      magSize: 8,
      reloadTime: 2200,
      auto: false,
      aimAssist: 0.03,
      sounds: { fire: 'deagleFire', reload: 'deagleReload' },
    },
  },
};

if (typeof module !== 'undefined') {
  module.exports = { PIECE_STATS };
}
