const PIECE_STATS = {
  p: {
    name: 'Pawn',
    hp: 150,
    speed: 12,
    jumpSpeed: 6,
    weapon: {
      type: 'pistol',
      damage: 12,
      fireRate: 300,
      magSize: 12,
      reloadTime: 1500,
      auto: false,
      dropoffStart: 15,
      dropoffEnd: 35,
      dropoffMin: 0.6,
      sounds: { fire: 'shoot', reload: 'reload' },
    },
  },
  n: {
    name: 'Knight',
    hp: 200,
    speed: 12,
    jumpSpeed: 11,
    weapon: {
      type: 'bow',
      damageMin: 15,
      damageMax: 50,
      chargeTime: 600,
      minChargeTime: 200,
      fireRate: 0,
      magSize: Infinity,
      reloadTime: 0,
      auto: false,
      sounds: { draw: 'bowDraw', fire: 'bowRelease' },
    },
  },
  b: {
    name: 'Bishop',
    hp: 275,
    speed: 9,
    jumpSpeed: 8,
    weapon: {
      type: 'shotgun',
      damagePerPellet: 8,
      pelletCount: 8,
      spread: 0.12,
      falloffStart: 6,
      falloffEnd: 16,
      fireRate: 800,
      magSize: 5,
      reloadTime: 600,
      reloadPerShell: true,
      auto: false,
      sounds: { fire: 'shotgunFire', pump: 'shotgunPump', reload: 'shotgunShell' },
    },
  },
  r: {
    name: 'Rook',
    hp: 350,
    speed: 8,
    jumpSpeed: 9,
    weapon: {
      type: 'sniper',
      damage: 70,
      fireRate: 1200,
      magSize: 5,
      reloadTime: 3500,
      auto: false,
      unscopedSpread: 0.15,
      jumpingSpread: 0.3,
      scopedAimAssist: 0.15,
      sounds: { fire: 'sniperFire', bolt: 'sniperBolt', scope: 'sniperScope', reload: 'sniperReload' },
    },
  },
  q: {
    name: 'Queen',
    hp: 425,
    speed: 6,
    jumpSpeed: 7,
    weapon: {
      type: 'ar',
      damage: 14,
      fireRate: 100,
      magSize: 30,
      reloadTime: 2800,
      auto: true,
      adsSpreadReduction: 0.5,
      dropoffStart: 18,
      dropoffEnd: 40,
      dropoffMin: 0.65,
      sounds: { fire: 'arFire', reload: 'arReload' },
    },
  },
  k: {
    name: 'King',
    hp: 500,
    speed: 6,
    jumpSpeed: 7,
    weapon: {
      type: 'minigun',
      damage: 4,
      fireRate: 60,
      magSize: 100,
      reloadTime: 5000,
      auto: true,
      spinupTime: 500,
      dropoffStart: 12,
      dropoffEnd: 30,
      dropoffMin: 0.5,
      sounds: { fire: 'minigunFire', reload: 'minigunReload', spinup: 'minigunSpinup', winddown: 'minigunWinddown' },
    },
  },
};

if (typeof module !== 'undefined') {
  module.exports = { PIECE_STATS };
}
